go.mod: Update cgroups dep to 0.0.7 and fix tests
This new version includes fixes for EPBF fd leaks:
	https://github.com/opencontainers/cgroups/pull/60

Let's update to it.

However, the Stats() method was added in the new release to the
interface, so tests were failing with:
	# github.com/opencontainers/runc/libcontainer [github.com/opencontainers/runc/libcontainer.test]
./container_linux_test.go:125:18: cannot use &mockCgroupManager{…} (value of type *mockCgroupManager) as cgroups.Manager value in struct literal: *mockCgroupManager does not implement cgroups.Manager (missing method Stats)

Let's add the method to the mock too.

In the future, probably the mock should come from the cgroups module.

Signed-off-by: Rodrigo Campos <rodrigo@amutable.com>